import { Property } from './types';

export const properties: Property[] = [
  {
    id: '1',
    title: 'Bedroom',
    description: 'A good bedroom offers a serene and cozy retreat, combining restful ambiance with functional comfort for peaceful sleep and relaxation.',
    location: 'Beverly Hills, CA',
    category: 'historical',
    images: [
      '/images/room1.jpeg',
      '/images/room4.jpeg',
      // '/images/room3.jpeg',
    ],
    videoUrl: 'https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_1mb.mp4',
    features: ['BedRoom'],
    area: 15000,
    price: 25000,
    featured: true,
  },
  {
    id: '2',
    title: 'Dining Hall',
    description: 'A well-designed dining hall blends elegance and comfort, featuring warm lighting, tasteful décor, and ample space for shared meals and meaningful conversations.',
    location: 'Malibu, CA',
    category: 'modern',
    images: [
        '/images/hall.jpeg',
        '/images/out1.jpeg',
        '/images/out2.jpeg',
    ],
    features: ['Dining Hall'],
    area: 8500,
    price: 18000,
    featured: true,
  },
  {
    id: '3',
    title: 'Industrial Loft Complex',
    description: 'Raw industrial spaces with exposed brick, steel beams, and dramatic lighting perfect for fashion shoots and urban commercials.',
    location: 'Downtown LA',
    category: 'commercial',
    images: [
      '/images/temp2.jpeg',
      '/images/temp1.jpeg',
      '/images/temp3.jpeg',
      '/images/temp4.jpeg',
    ],
    features: ['Exposed Brick', 'High Ceilings', 'Natural Light', 'Loading Dock', 'Open Floor Plan'],
    area: 12000,
    price: 15000,
    featured: false,
  },
  {
    id: '4',
    title: 'Traditional Entrance with Modern Accents',
    description: 'A beautifully carved wooden door framed by intricate floral detailing stands as a regal centerpiece.',
    location: 'Pasadena, CA',
    category: 'historical',
    images: [
      '/images/temp6.jpeg',
      '/images/temp5.jpeg',
      '/images/temp7.jpeg',
      '/images/temp8.jpeg',
    ],
    features: ['Period Furnishings', 'Grand Piano', 'Secret Passages', 'Conservatory', 'Formal Dining'],
    area: 9200,
    price: 20000,
    featured: true,
  },
];